dependencies:
  - name: inventory-management-ui-mk
    version: 1.0.0-4
    repository: >-
      http://artifactory.mooc-three-rhos-cluster.jp-tok.containers.appdomain.cloud/artifactory/generic-local/mooc-team-three/
